### ISSUE TITLE
Write simplified and targeted maintainers guide, style guide and contributor guide that are user friendly.

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/opensource#1]

**Comment by lnielsen** [comment]
Initial work in:

- [x] http://invenio.readthedocs.io/en/latest/community/contribution-guide.html
- [ ] http://invenio.readthedocs.io/en/latest/community/style-guide.html
- [ ] http://invenio.readthedocs.io/en/latest/community/maintainers-guide/index.html
- [ ] Propagate contribution guide to all Invenio repositories.

**Comment by jbenito3** [comment]
I would be ok with the current style guide and maintainers guide. I think it could be considered a work that it will be on-going forever along with the changes in the community.
What about the contribution guide?
