### ISSUE TITLE
Setup team building event (common one day sprint).

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/opensource#24]

**Comment by lnielsen** [comment]
Ideas from DevForum:

- Hack Invenio to find security vulnerabilities.
- Build some tools for maintainers.
- Bots/checks/etc to remind maintainers about tasks.
- Setup a standalone CI system to have more computing power.
- Tool for improving tracking
- Deploy Invenio on Amazon.
- Run Invenio on RaspberryPi.
- Try to do things you don't known (everybody write ideas on a paper and put in a hat, you then drag out an idea from the hat).
- Create an easter egg inside Invenio.

**Comment by jbenito3** [comment]
solved with invenio sprints and other when-needed sprints
