### ISSUE TITLE
Write how-to's/templates for implementing best practice

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/opensource#56]
- Make a collection of good examples from existing documentation.
- Provide templates for getting started: code, figures, paragraphs, sections
- Provide templates with predefined structure and questions that he write should answer - eg. who is your audience, what is their knowledge (content guideline should help), what is your outline, what should people know at the end.

**Comment by saragon02** [comment]
Closing as part of repo updates, May 2024
