### ISSUE TITLE
chat: improve Discord channel setup

### ISSUE THREAD

**Issue by diegodelemos** [inveniosoftware/opensource#68]
Look at existing open source projects Discord servers and improve Invenio's one:
- https://discordapp.com/invite/t6rrQZH

For example, improve the experience when people joins the chat:
![image](https://user-images.githubusercontent.com/9035606/90771025-fb0b3480-e2f2-11ea-83dd-d6b9a796ac4c.png)

**Comment by FlorianCassayre** [comment]
Discord calls this (recent) feature "**Welcome Screen**".

For the technical details:
- This feature requires the activation of the "[Community Server Settings](https://support.discord.com/hc/en-us/articles/360047132851)". I don't know if it is already the case; but if not, the spirit of this server seems to fit the requirements anyway.
- Once this is done it is easy to enable the feature as described [here](https://support.discord.com/hc/en-us/articles/360047132851).

**Comment by ntarocco** [comment]
![_rdm-internal_-_Discord](https://user-images.githubusercontent.com/2089455/90788465-22b7c800-e306-11ea-9af1-66a56f5dea0f.png)

**Comment by ntarocco** [comment]
Done! 🚀
